/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import br.com.AVL.AvlNode;
import br.com.AVL.AvlTree;
import br.com.FileManager.FileManager;
import br.com.Lista.Lista;
import br.com.Lista.EmptyListException;
import br.com.Lista.NoLista;

import javax.swing.*;
import java.awt.*;
import java.io.IOException;
import java.sql.SQLOutput;
import java.util.Scanner;

/**
 *
 * @author D4rks
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("./src/main/java/Files/skull 2.png")); // NOI18N
        jLabel1.setText("jLabel1");

        jButton1.setText("Carregar Arquivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jButton1)
                                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jButton1))
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setText("List and Tree Project");
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(jLabel2))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        FileManager.OpenArq(this);
        String linha = "";
        while (linha != null) {
            linha = FileManager.Llinha();
            if (linha != null) {
                list.insereNoFim(linha);
                t.insert(linha);
            }
        }
        FileManager.ArqClose();
        menu();
    }

    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        Lista list = new Lista("Professores");
        AvlTree t = new AvlTree();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Main tela = new Main();
                tela.setLocationRelativeTo(null);
                tela.setVisible(true);
            }
        });


    }

    public void menu (){
        Scanner in = new Scanner(System.in);
        int op2,pos;
        String nm;
        System.out.println("Deseja Continuar ?");
        String nada = in.next();
        for(int i=0 ; i<30 ; i++){
            System.out.println();
        }
        int op = -1;
        while (op<1 || op>2) {
            System.out.println("Escolha sua Opcao : ");
            System.out.println("1 - Lista");
            System.out.println("2 - Arvore AVL");
            op = in.nextInt();
        }
        if (op==1){
            op=-1;
            while(op!=0){
                System.out.println("------- Lista -------");
                System.out.println("1 - Inserir Elemento");
                System.out.println("2 - Remover Elemento");
                System.out.println("3 - Buscar Elemento");
                System.out.println("4 - Tamanho da lista");
                System.out.println("5 - Imprimir Lista");
                System.out.println("0 - Sair de Lista");
                op = in.nextInt();
                switch (op) {
                    case 1 :
                        System.out.println("1 - Inserir no inicio");
                        System.out.println("2 - Inserir no Fim");
                        System.out.println("3 - Inserir em posicao");
                        op2 = in.nextInt();
                        if (op2 == 1){
                            System.out.print("Entre com o nome: ");
                            list.insereNoInicio(in.nextLine());
                        }else if (op2 == 2){
                            System.out.print("Entre com o nome: ");
                            list.insereNoFim(in.nextLine());
                        }else if (op2 == 3){
                            System.out.print("Entre com o nome: ");
                            nm = in.nextLine();
                            System.out.print("Entre com a posicao: ");
                            pos = in.nextInt();
                            list.insertAtPosicao(pos,nm);
                        }
                        break;
                    case 2 :
                        System.out.println("1 - Remover no inicio");
                        System.out.println("2 - Remover no Fim");
                        System.out.println("3 - Remover em posicao");
                        op2 = in.nextInt();
                        if (op2 == 1){
                            try{
                                nm = list.removeNoInicio();
                                System.out.printf(nm," Removido\n");
                            }catch (EmptyListException e){
                            }
                        }else if (op2 == 2){
                            try{
                                nm = list.removeNoFim();
                                System.out.printf(nm," Removido\n");
                            }catch (EmptyListException e){
                            }
                        }else if (op2 == 3){
                            System.out.print("Entre com a posicao: ");
                            pos = in.nextInt();
                            try {
                                if (list.removeFromPosicao(pos)){
                                    System.out.println("Elemento Removido");
                                }else {
                                    System.out.println("Erro ao Remover");
                                }
                            }catch (EmptyListException e){

                            }
                        }
                        break;
                    case 3:
                        System.out.print("Entre com o nome: ");
                        list.buscaElemento(in.nextLine());
                        break;
                    case 4:
                        System.out.println(list.imprimeTamanho());
                        break;
                    case 5:
                        list.print();
                }
            }
        }else{
            op=-1;
            while(op!=0){
                System.out.println("------- Arvore AVL -------");
                System.out.println("1 - Inserir Elemento");
                System.out.println("2 - Remover Elemento");
                System.out.println("3 - Buscar Elemento");
                System.out.println("4 - Imprimir Arvore");
                System.out.println("0 - Sair");
                op = in.nextInt();
                switch (op){
                    case 1:
                        System.out.print("Entre com o nome: ");
                        nm = in.nextLine();
                        t.insert(nm);
                        break;
                    case 2:
                        System.out.println("Error :X :X :X :X");
                        break;
                    case 3:
                        System.out.print("Entre com o nome: ");
                        nm = in.next();
                        AvlNode el = new AvlNode();
                        el = t.search(nm);
                        if(el != null){
                            System.out.println("Nome Pertecente a Arvore");
                        }else{
                            System.out.println("Nome náo encontrado");
                        }
                        break;
                    case 4:
                        System.out.println("------- Imprimir -------");
                        System.out.println("1 - Sair e Mostrar Arvore AVL");
                        System.out.println("2 - In Order");
                        System.out.println("3 - Pre Order");
                        op2 = in.nextInt();
                        if (op2==1){

                        }else if (op2==2){
                            t.inorder();
                            System.out.println();
                        }else if (op2==3){
                            t.preorder();
                            System.out.println();
                        }else{
                            System.out.println("Error :X :X :X :X");
                        }
                        break;
                }
            }
            t.displayTree();
        }

    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    static Lista list = new Lista("Professores");
    static AvlTree t = new AvlTree();
    // End of variables declaration
}
